name: Deploy to cloud run
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # setup the google cloud
      - name: Setup google cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      # Authenticate Docker with GCP Artifact Registry
      - name: Authenticate Docker
        run: gcloud auth configure-docker

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-node-backend"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      
       # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-node-backend"
          gcloud run deploy hello-node-backend \
            --image $IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 512Mi